# Generated by Django 3.1.2 on 2021-12-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('companyName', models.CharField(blank=True, max_length=200, null=True)),
                ('companyShortName', models.CharField(blank=True, max_length=200, null=True)),
                ('openingHours', models.CharField(blank=True, max_length=200, null=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('telephoneCompany', models.CharField(blank=True, max_length=200, null=True)),
                ('telephoneRefund', models.CharField(blank=True, max_length=200, null=True)),
                ('telephoneEmergency', models.CharField(blank=True, max_length=200, null=True)),
                ('emailInfo', models.EmailField(blank=True, max_length=200, null=True)),
                ('emailSupport', models.EmailField(blank=True, max_length=200, null=True)),
                ('emailRefund', models.EmailField(blank=True, max_length=200, null=True)),
                ('facebookLink', models.URLField(blank=True, null=True)),
                ('instragramLink', models.URLField(blank=True, null=True)),
                ('twitterLink', models.URLField(blank=True, null=True)),
                ('googlePlayStoreLink', models.URLField(blank=True, null=True)),
                ('appleStoreLink', models.URLField(blank=True, null=True)),
                ('websiteLink', models.URLField(blank=True, null=True)),
                ('logoImageLink1', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('logoImageLink2', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('logoImageLink3', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('onlyIconImageLink', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('faviconImageLink', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
