# Generated by Django 3.1.2 on 2021-12-29 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetails',
            old_name='Address',
            new_name='address',
        ),
    ]
