# Generated by Django 3.1.2 on 2022-01-03 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220103_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='api.product'),
        ),
        migrations.AlterField(
            model_name='price',
            name='text',
            field=models.CharField(choices=[('None', 'None'), ("On It's Own", "On It's Own"), ('Meal', 'Meal')], default=None, max_length=200),
        ),
    ]
