# Generated by Django 3.1.2 on 2022-01-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220105_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isHomeFeatured',
            field=models.BooleanField(default=False),
        ),
    ]
